version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./data/nginx/static:/home/app/web/project/static
      - ./data/nginx/media:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.web
    depends_on:
      - db
      - redis
      
  nginx:
    build: ./services/nginx
    volumes:
      - ./data/nginx/static:/home/app/web/project/static
      - ./data/nginx/media:/home/app/web/project/media
    ports:
      - 1337:80
    depends_on:
      - web

  db:
    image: postgres:13-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
    image: redis
    ports:
      - "6379:6379"
